chore: precommit hook should execute global hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,15 @@
 
-# run global hook if exists
-if [ -x "$HOME/.git-hooks/pre-commit.d/gitleaks" ]; then
-  "$HOME/.git-hooks/pre-commit.d/gitleaks"
+# run global hook
+GITLEAKS_HOOK="$HOME/.git-hooks/pre-commit.d/gitleaks"
+
+if [ -x "$GITLEAKS_HOOK" ]; then
+  if ! "$GITLEAKS_HOOK"; then
+    printf 'Global gitleaks pre-commit hook failed. Aborting commit.\n' >&2
+    exit 1
+  fi
+else
+  printf 'Error: Global gitleaks hook is not a file or not executable: %s\n' "$GITLEAKS_HOOK" >&2
+  exit 1
 fi
 
 # Get changed files in test/integrations/sources/
